language: php

php:
  - 5.6

install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)